micronaut:
  application:
    name: msTestLucho
  server:
    port: 8082    
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/luchoDB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'kasparov'
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create
netty:
  default:
    allocator:
      max-order: 3
